module.exports = {
  cs: {
    generalTitle: '📜 | OBECNÁ PRAVIDLA (15)',
    generalDesc: `**1.** Chovejte se k sobě s respektem a úctou.\n**2.** Zákaz jakékoliv formy diskriminace, rasismu či urážek.\n**3.** Respektujte soukromí ostatních uživatelů.\n**4.** Zákaz šíření cizích osobních údajů (doxxing).\n**5.** Nevyvolávejte hádky ani toxické diskuse.\n**6.** Nezneužívejte chyby nebo mezery v pravidlech serveru.\n**7.** Dodržujte platné zákony České/Slovenské republiky a EU.\n**8.** Sdílení nevhodného nebo nelegálního obsahu (NSFW/NSFL atd.) je přísně zakázáno.\n**9.** Moderátoři a Admini mají vždy poslední slovo a jejich rozhodnutí je nutné respektovat.\n**10.** Své stížnosti či neshody s admin týmem řešte pomocí ticketů, nikoliv veřejně v chatu.\n**11.** Zákaz politických, extremistických a náboženských diskusí a agendy.\n**12.** Zakázáno vydávat se za jiného uživatele, známé osobnosti nebo členy admin týmu.\n**13.** Zákaz reklamy a propagace jakéhokoliv druhu mimo určené kanály nebo bez povolení.\n**14.** Netrollujte a nekazte úmyslně zážitek ostatním.\n**15.** Používejte zdravý selský rozum – Pokud nějaká konkrétní situace není pokryta pravidly, platí zdravý rozum a etika.`,
    
    discordTitle: '💬 | DISCORD PRAVIDLA (18)',
    discordDesc: `**1.** Zákaz nevyžádaného pingování (zmiňování) členů a obzvlášť Admin týmu bez pádného důvodu.\n**2.** Zákaz pingování velkých rolí, jako je @everyone nebo @here.\n**3.** Profilový obrázek a banner nesmí obsahovat nevhodný, sprostý nebo rasistický obsah.\n**4.** Přezdívka musí být snadno čitelná (označitelná) a nesmí obsahovat vulgární znaky či slova.\n**5.** Neposílejte do chatu spam (opakované nesmyslné zprávy).\n**6.** Neposílejte do chatu flood (rozsekávání jedné zprávy do desítek krátkých zpráv).\n**7.** Zákaz nadměrného používání velkých písmen (CAPS LOCK).\n**8.** Udržujte kanály k jejich určeným účelům (off-topic, příkazy botů, memy ...).\n**9.** Neposílejte odkazy na podezřelé, phishing nebo nebezpečné stránky a soubory.\n**10.** Zákaz "Ghost Pingování" (úmyslné označení a rychlé smazání zprávy).\n**11.** Ve voice kanálech nevydávejte nepříjemné zvuky (foukání do mikrofonu, řev, soundboard spam).\n**12.** Nepoužívejte voice changery nebo jiné rušivé efekty hlasu bez souhlasu ostatních.\n**13.** Pokud si pouštíte hudbu, buďte ohleduplní k ostatním posluchačům.\n**14.** Zákaz streamování nevhodných či porušujících autorská práva videí ve voice kanálech.\n**15.** Zákaz žebrání o role, speciální práva či výhody v chatu.\n**16.** Chovejte se slušně a omezte vulgarismy v textech zpráv i v hlase na minimum.\n**17.** Nenarušujte cizí probíhající konverzace ve voice kanálech nevhodným skákáním do řeči.\n**18.** Respektujte oficiální TOS (Podmínky služby) a Pokyny komunity samotné platformy Discord.`,

    serverTitle: '🛡️ | SERVEROVÁ PRAVIDLA (10)',
    serverDesc: `**1.** Zákaz používání jakýchkoli neoficiálních nebo neautorizovaných klientů, cheatů nebo hacků.\n**2.** Je zakázáno zneužívat chyby a bugy nastavení serveru. Naopak je hlaste admin týmu.\n**3.** Respektujte všechny ostatní hráče a úmyslně jim nekažte prožitek z hraní.\n**4.** Zákaz Griefingu: Není dovoleno bezdůvodně ničit ani poškozovat majetek a snahu ostatních.\n**5.** Vytváření lag-mašin, které uměle nebo úmyslně zpomalují chod serveru, se tvrdě trestá.\n**6.** Jakékoli formy podvodů v dohodách mezi hráči (Scamming) jsou přísně zakázány.\n**7.** Vaše stroje a automatizace nesmí svým obřím provozem nepřiměřeně zatěžovat výkon celého serveru.\n**8.** Hrajte fair-play napříč všemi eventy a situacemi, snažíme se tu vytvořit fajn komunitu.\n**9.** Na serveru je povolen pouze jeden herní účet na uživatele (tzv. zákaz Altů bez povolení/výjimky).\n**10.** Zákaz obchodovat za reálné peníze s virtuálními předměty serveru mezi hráči černým trhem.`,

    mcTitle: '⛏️ | MINECRAFTOVÁ PRAVIDLA (14)',
    mcDesc: `**1.** X-Ray a jakékoliv modifikace (texturepacky) zobrazující nepovoleně bloky a jeskyně jsou přísně zakázány.\n**2.** Baritone (automatické těžení nebo cesta) a jiné botovací klienty se tvrdě trestají zabanováním.\n**3.** AFkování a farmení: Povoleno, ale u velkých a přetěžujících farem můžete být vyzváni k jejich limitaci.\n**4.** Zákaz jakýchkoli forem duplikování itemů, bloků nebo XP.\n**5.** Krádeže věcí a peněz ze soukromých zabezpečených beden hráčů a obydlí jsou přísně zakázány.\n**6.** Nechejte celou oblast spawnu (začátku) netknutou a hezkou, zákázáno stavět nebo ničit přírodu extrémně blízko spawnu.\n**7.** Zakázano stavět nevhodné a pohoršující stavby.\n**8.** Zabíjet ostatní hráče (PVP) bez předchozí domluvy v lokacích k tomu neurčených je zakázáno (tzv. zákaz RDM).\n**9.** Mějte adekvátní chování. Trolling a baiting (smyšlené lákaní do teleportační pasti atd.) je nepovolen.\n**10.** Kácení stromů musí být kompletní zespoda nehoru – nenechávejte létající kusy listů či desky stromů trčet ve vzduchu.\n**11.** Neničte hezký vzhled přírody. Ošklivé sloupy do nebe pro rozhlednutí ihned zničte za sebou.\n**12.** A-Team má právo upravit vaši stavbu/zvířectvo v případě ohrožení lagováním mapy (TPS dropy).\n**13.** Zákaz spamování chatu v Minecraftu i v MSG (soukromé zprávy).\n**14.** Zodpovědnost za svůj soukromý herní postavu nesete výlučně vy (když se hackne účet nebo hraje sourozenec – to je váš problém).`
  },
  sk: {
    generalTitle: '📜 | VŠEOBECNÉ PRAVIDLÁ (15)',
    generalDesc: `**1.** Správajte sa k sebe s rešpektom a úctou.\n**2.** Zákaz akejkoľvek formy diskriminácie, rasizmu či urážok.\n**3.** Rešpektujte súkromie ostatných používateľov.\n**4.** Zákaz šírenia cudzích osobných údajov (doxxing).\n**5.** Nevyvolávajte hádky ani toxické diskusie.\n**6.** Nezneužívajte chyby alebo medzery v pravidlách servera.\n**7.** Dodržujte platné zákony Českej/Slovenskej republiky a EÚ.\n**8.** Zdieľanie nevhodného alebo nelegálneho obsahu (NSFW/NSFL atď.) je prísne zakázané.\n**9.** Moderátori a Admini majú vždy posledné slovo a ich rozhodnutia je nutné rešpektovať.\n**10.** Svoje sťažnosti či nezhody s admin tímom riešte pomocou ticketov, nie verejne v chate.\n**11.** Zákaz politických, extrémistických a náboženských diskusií a agendy.\n**12.** Je zakázané vydávať sa za iného používateľa, známe osobnosti alebo členov admin tímu.\n**13.** Zákaz reklamy a propagácie akéhokoľvek druhu mimo určené kanály alebo bez povolenia.\n**14.** Netrollujte a nekazte úmyselne zážitok ostatným.\n**15.** Používajte zdravý rozum – Ak nejaká konkrétna situácia nie je pokrytá pravidlami, platí zdravý rozum a etika.`,
    
    discordTitle: '💬 | DISCORD PRAVIDLÁ (18)',
    discordDesc: `**1.** Zákaz nevyžiadaného pingovania (zmieňovania) členov a obzvlášť Admin tímu bez pádneho dôvodu.\n**2.** Zákaz pingovania veľkých rolí, ako je @everyone alebo @here.\n**3.** Profilový obrázok a banner nesmie obsahovať nevhodný, vulgárny alebo rasistický obsah.\n**4.** Prezývka musí byť ľahko čitateľná (označiteľná) a nesmie obsahovať vulgárne znaky či slová.\n**5.** Neposielajte do chatu spam (opakované nezmyselné správy).\n**6.** Neposielajte do chatu flood (rozsekávanie jednej správy do desiatok krátkych správ).\n**7.** Zákaz nadmerného používania veľkých písmen (CAPS LOCK).\n**8.** Udržujte kanály na ich určené účely (off-topic, príkazy botov, mémy ...).\n**9.** Neposielajte odkazy na podozrivé, phishing alebo nebezpečné stránky a súbory.\n**10.** Zákaz "Ghost Pingovania" (úmyselné označenie a rýchle zmazanie správy).\n**11.** Vo voice kanáloch nevydávajte nepríjemné zvuky (fúkanie do mikrofónu, rev, soundboard spam).\n**12.** Nepoužívajte voice changery alebo iné rušivé efekty hlasu bez súhlasu ostatných.\n**13.** Pokiaľ si púšťate hudbu, buďte ohľaduplní k ostatným poslucháčom.\n**14.** Zákaz streamovania nevhodných či porušujúcich autorské práva videí vo voice kanáloch.\n**15.** Zákaz žobrania o roly, špeciálne práva či výhody v chate.\n**16.** Správajte sa slušne a obmedzte vulgarizmy v textoch správ aj v hlase na minimum.\n**17.** Nenarušujte cudzie prebiehajúce konverzácie vo voice kanáloch nevhodným skákaním do reči.\n**18.** Rešpektujte oficiálne TOS (Podmienky služby) a Pokyny komunity samotnej platformy Discord.`,

    serverTitle: '🛡️ | SERVEROVÉ PRAVIDLÁ (10)',
    serverDesc: `**1.** Zákaz používania akýchkoľvek neoficiálnych alebo neautorizovaných klientov, cheatov alebo hackov.\n**2.** Je zakázané zneužívať chyby a bugy v nastavení servera. Naopak, hláste ich admin tímu.\n**3.** Rešpektujte všetkých ostatných hráčov a úmyselne im nekazte zážitok z hrania.\n**4.** Zákaz Griefingu: Nie je dovolené bezdôvodne ničiť ani poškodzovať majetok a snahu ostatných.\n**5.** Vytváranie lag-mašín, ktoré umelo alebo úmyselne spomaľujú chod servera, sa tvrdo trestá.\n**6.** Akékoľvek formy podvodov v dohodách medzi hráčmi (Scamming) sú prísne zakázané.\n**7.** Vaše stroje a automatizácia nesmú svojou obrovskou prevádzkou neprimerane zaťažovať výkon celého servera.\n**8.** Hrajte fair-play naprieč všetkými eventmi a situáciami, snažíme sa tu vytvoriť fajn komunitu.\n**9.** Na serveri je povolený len jeden herný účet na používateľa (tzv. zákaz Altov bez povolenia/výnimky).\n**10.** Zákaz obchodovať za reálne peniaze s virtuálnymi predmetmi servera medzi hráčmi na čiernom trhu.`,

    mcTitle: '⛏️ | MINECRAFTOVÉ PRAVIDLÁ (14)',
    mcDesc: `**1.** X-Ray a akékoľvek modifikácie (texturepacky) zobrazujúce nepovolene bloky a jaskyne sú prísne zakázané.\n**2.** Baritone (automatické ťaženie alebo cesta) a iné botovacie klienty sa tvrdo trestajú zabanovaním.\n**3.** AFkovanie a farmenie: Povolené, ale u veľkých a preťažujúcich fariem môžete byť vyzvaní k ich limitácii.\n**4.** Zákaz akýchkoľvek foriem duplikovania itemov, blokov alebo XP.\n**5.** Krádeže vecí a peňazí zo súkromných zabezpečených truhlíc hráčov a obydlí sú prísne zakázané.\n**6.** Nechajte celú oblasť spawnu (začiatku) nedotknutú a peknú, je zakázané stavať alebo ničiť prírodu extrémne blízko spawnu.\n**7.** Zakázané stavať nevhodné a pohoršujúce stavby.\n**8.** Zabíjať ostatných hráčov (PVP) bez predchádzajúcej dohody v lokáciách na to neurčených je zakázané (tzv. zákaz RDM).\n**9.** Majte adekvátne správanie. Trolling a baiting (vymyslené lákanie do teleportačnej pasce atď.) je nepovolený.\n**10.** Rúbanie stromov musí byť kompletné zdola nahor – nenechávajte lietajúce kusy listov či dosky stromov trčať vo vzduchu.\n**11.** Neničte pekný vzhľad prírody. Škaredé stĺpy do neba pre rozhliadnutie ihneď zničte za sebou.\n**12.** A-Team má právo upraviť vašu stavbu/zvieratstvo v prípade ohrozenia lagovaním mapy (TPS dropy).\n**13.** Zákaz spamovania chatu v Minecrafte aj v MSG (súkromné správy).\n**14.** Zodpovednosť za svoju súkromnú hernú postavu nesiete výlučne vy (keď sa hackne účet alebo hrá súrodenec – to je váš problém).`
  },
  en: {
    generalTitle: '📜 | GENERAL RULES (15)',
    generalDesc: `**1.** Treat each other with respect and dignity.\n**2.** No discrimination, racism, or insults of any kind.\n**3.** Respect the privacy of other users.\n**4.** No distributing other people's personal information (doxxing).\n**5.** Do not provoke arguments or toxic discussions.\n**6.** Do not exploit mistakes or loopholes in the server rules.\n**7.** Abide by the applicable laws of the Czech/Slovak Republic and the EU.\n**8.** Sharing inappropriate or illegal content (NSFW/NSFL, etc.) is strictly forbidden.\n**9.** Moderators and Admins always have the final say; their decisions must be respected.\n**10.** Resolve complaints or disagreements with the admin team via tickets, not publicly in chat.\n**11.** No political, extremist, or religious discussions and agendas.\n**12.** Impersonation of other users, celebrities, or admin team members is forbidden.\n**13.** No advertising or promotion of any kind outside designated channels or without permission.\n**14.** Do not troll or intentionally ruin the experience for others.\n**15.** Use common sense – If a specific situation is not covered by the rules, common sense and ethics apply.`,
    
    discordTitle: '💬 | DISCORD RULES (18)',
    discordDesc: `**1.** No unsolicited pinging (mentioning) of members, especially the Admin team, without a valid reason.\n**2.** No pinging of large roles, such as @everyone or @here.\n**3.** Profile pictures and banners must not contain inappropriate, offensive, or racist content.\n**4.** Nicknames must be easily readable (mentionable) and contain no vulgar characters or words.\n**5.** Do not spam the chat (repeated meaningless messages).\n**6.** Do not flood the chat (splitting one message into dozens of short messages).\n**7.** No excessive use of capital letters (CAPS LOCK).\n**8.** Keep channels to their designated purposes (off-topic, bot commands, memes...).\n**9.** Do not post links to suspicious, phishing, or dangerous sites and files.\n**10.** No "Ghost Pinging" (mentioning and quickly deleting the message).\n**11.** Do not make annoying noises in voice channels (blowing into the mic, screaming, soundboard spam).\n**12.** Do not use voice changers or other disruptive voice effects without the consent of others.\n**13.** If playing music, be considerate of other listeners.\n**14.** Do not stream inappropriate or copyrighted videos in voice channels.\n**15.** No begging for roles, special rights, or privileges in the chat.\n**16.** Behave politely and keep vulgarities in text and voice to a minimum.\n**17.** Do not interrupt ongoing conversations in voice channels by jumping in inappropriately.\n**18.** Respect the official TOS (Terms of Service) and Community Guidelines of the Discord platform itself.`,

    serverTitle: '🛡️ | SERVER RULES (10)',
    serverDesc: `**1.** No using unofficial or unauthorized clients, cheats, or hacks.\n**2.** Exploiting server bugs and glitches is forbidden. Report them to the admin team instead.\n**3.** Respect all other players and do not intentionally ruin their gaming experience.\n**4.** No Griefing: Destroying or damaging others' property and efforts without reason is not allowed.\n**5.** Creating lag machines that artificially or intentionally slow down the server is severely punished.\n**6.** Any form of fraud in agreements between players (Scamming) is strictly prohibited.\n**7.** Your machines and automation must not disproportionately burden the server's performance.\n**8.** Play fair-play across all events and situations; we are trying to build a nice community.\n**9.** Only one game account per user is allowed (no Alts without permission/exception).\n**10.** No black market trading of virtual server items between players for real money.`,

    mcTitle: '⛏️ | MINECRAFT RULES (14)',
    mcDesc: `**1.** X-Ray and any modifications (texture packs) that illegally display blocks and caves are strictly prohibited.\n**2.** Baritone (automatic mining or pathing) and other botting clients are severely punished with a ban.\n**3.** AFKing and farming: Allowed, but you may be asked to limit very large and lagging farms.\n**4.** Any forms of duplicating items, blocks, or XP are prohibited.\n**5.** Stealing items and money from players' private secured chests and homes is strictly forbidden.\n**6.** Leave the entire spawn area untouched and beautiful; building or destroying nature extremely close to spawn is forbidden.\n**7.** Building inappropriate and offensive structures is forbidden.\n**8.** Killing other players (PVP) without prior agreement in unauthorized locations is prohibited (no RDM).\n**9.** Behave appropriately. Trolling and baiting (e.g., fake luring into teleport traps) is not allowed.\n**10.** Tree chopping must be complete from bottom to top – do not leave floating leaves or wooden blocks in the air.\n**11.** Do not destroy the beauty of nature. Destroy ugly pillar towers immediately after looking around.\n**12.** A-Team has the right to modify your build/animals in case of server lag threats (TPS drops).\n**13.** No spamming the chat in Minecraft or in MSG (private messages).\n**14.** You are solely responsible for your private game character (if the account is hacked or a sibling plays – it's your problem).`
  },
  de: {
    generalTitle: '📜 | ALLGEMEINE REGELN (15)',
    generalDesc: `**1.** Behandelt einander mit Respekt und Würde.\n**2.** Jegliche Form von Diskriminierung, Rassismus oder Beleidigung ist verboten.\n**3.** Respektiert die Privatsphäre der anderen Benutzer.\n**4.** Die Weitergabe fremder persönlicher Daten (Doxxing) ist untersagt.\n**5.** Provoziert keine Streitereien oder toxische Diskussionen.\n**6.** Nutzt keine Fehler oder Lücken in den Serverregeln aus.\n**7.** Haltet die geltenden Gesetze der EU und lokalen Behörden ein.\n**8.** Das Teilen von unangemessenen oder illegalen Inhalten (NSFW/NSFL usw.) ist strengstens verboten.\n**9.** Moderatoren und Admins haben immer das letzte Wort, ihre Entscheidungen müssen respektiert werden.\n**10.** Klärt Beschwerden oder Unstimmigkeiten mit dem Admin-Team über Tickets, nicht öffentlich im Chat.\n**11.** Keine politischen, extremistischen oder religiösen Diskussionen.\n**12.** Es ist verboten, sich als ein anderer Benutzer, eine bekannte Persönlichkeit oder ein Mitglied des Admin-Teams auszugeben.\n**13.** Keine Werbung jedweder Art außerhalb der dafür vorgesehenen Kanäle oder ohne Erlaubnis.\n**14.** Kein Trollen oder absichtliches Ruinieren des Spielerlebnisses für andere.\n**15.** Benutzt den gesunden Menschenverstand – Wenn eine spezielle Situation nicht durch die Regeln abgedeckt ist, gelten gesunder Menschenverstand und Ethik.`,
    
    discordTitle: '💬 | DISCORD REGELN (18)',
    discordDesc: `**1.** Kein unerwünschtes Pingen von Mitgliedern, besonders das Admin-Team, ohne triftigen Grund.\n**2.** Kein Pingen von großen Rollen wie @everyone oder @here.\n**3.** Profilbild und Banner dürfen keine unangemessenen, beleidigenden oder rassistischen Inhalte aufweisen.\n**4.** Spitznamen müssen lesbar (erwähnbar) sein und dürfen keine vulgären Zeichen oder Wörter enthalten.\n**5.** Spammt den Chat nicht voll (wiederholte sinnlose Nachrichten).\n**6.** Flutet den Chat nicht (Aufteilen einer Nachricht in dutzende kurze Nachrichten).\n**7.** Keine übermäßige Nutzung von Großbuchstaben (CAPS LOCK).\n**8.** Behaltet die Kanäle für ihren vorgesehenen Zweck bei (Off-Topic, Bot-Befehle, Memes...).\n**9.** Keine Links zu verdächtigen, Phishing- oder gefährlichen Seiten posten.\n**10.** Kein "Ghost Pinging" (absichtliches Erwähnen und schnelles Löschen der Nachricht).\n**11.** Keine nervigen Geräusche in Sprachkanälen (ins Mikrofon pusten, schreien, Soundboard-Spam).\n**12.** Verwendet keine Voice Changer ohne die Zustimmung anderer.\n**13.** Wenn ihr Musik abspielt, nehmt Rücksicht auf andere Zuhörer.\n**14.** Das Streamen unangemessener oder urheberrechtlich geschützter Videos in Sprachkanälen ist verboten.\n**15.** Kein Betteln nach Rollen, Sonderrechten oder Privilegien im Chat.\n**16.** Verhaltet euch höflich und minimiert Vulgaritäten in Textnachrichten und im Sprachchat.\n**17.** Stört keine laufenden Gespräche in Sprachkanälen durch unangebrachtes Dazwischenreden.\n**18.** Respektiert die offiziellen TOS (Nutzungsbedingungen) und Community-Richtlinien der Plattform Discord.`,

    serverTitle: '🛡️ | SERVER REGELN (10)',
    serverDesc: `**1.** Die Nutzung von inoffiziellen oder unautorisierten Clients, Cheats oder Hacks ist verboten.\n**2.** Das Ausnutzen von Fehlern und Bugs ist verboten. Meldet diese stattdessen dem Admin-Team.\n**3.** Respektiert alle anderen Spieler und zerstört nicht absichtlich ihr Spielerlebnis.\n**4.** Kein Griefing: Die grundlose Zerstörung oder Beschädigung von fremdem Eigentum ist nicht gestattet.\n**5.** Das Erstellen von Lag-Maschinen, die den Server künstlich verlangsamen, wird hart bestraft.\n**6.** Jegliche Form von Betrug bei Vereinbarungen zwischen Spielern (Scamming) ist strengstens untersagt.\n**7.** Eure Maschinen und Automatisierungen dürfen den Server nicht unverhältnismäßig belasten.\n**8.** Spielt fair; wir versuchen, eine nette Community aufzubauen.\n**9.** Es ist nur ein Spielkonto pro Benutzer erlaubt (keine Alts ohne Erlaubnis/Ausnahme).\n**10.** Kein Schwarzmarkthandel mit virtuellen Server-Gegenständen zwischen Spielern für echtes Geld.`,

    mcTitle: '⛏️ | MINECRAFT REGELN (14)',
    mcDesc: `**1.** X-Ray und jegliche Modifikationen, die unrechtmäßig Blöcke und Höhlen anzeigen, sind strengstens verboten.\n**2.** Baritone (automatisches Abbauen) und andere Bot-Clients werden streng mit einem Bann bestraft.\n**3.** AFK und Farmen: Erlaubt, aber bei sehr großen und laggenden Farmen könnt ihr aufgefordert werden, diese zu begrenzen.\n**4.** Jegliche Form der Duplizierung von Items, Blöcken oder XP ist verboten.\n**5.** Das Stehlen von Gegenständen und Geld aus privaten Truhen ist strengstens untersagt.\n**6.** Lasst das Spawn-Gebiet unberührt; Bauen oder Zerstören von Natur extrem nah am Spawn ist verboten.\n**7.** Das Bauen unangemessener oder anstößiger Strukturen ist verboten.\n**8.** Das Töten anderer Spieler (PVP) ohne vorherige Zustimmung ist verboten (kein RDM).\n**9.** Keine Trolls oder Baits (z.B. falsches Locken in Teleport-Fallen).\n**10.** Bäume müssen komplett von unten nach oben abgebaut werden – keine fliegenden Blätter oder Holzblöcke hinterlassen.\n**11.** Zerstört nicht die Natur. Baut hässliche Hilfspfeiler nach dem Umschauen sofort wieder ab.\n**12.** Das A-Team hat das Recht, eure Bauten/Tiere bei Server-Lag (TPS-Drops) anzupassen.\n**13.** Kein Spammen im Ingame-Chat oder in MSG (Private Nachrichten).\n**14.** Ihr seid allein für euren Account verantwortlich (auch wenn er gehackt wurde oder ein Geschwisterteil spielt).`
  },
  pl: {
    generalTitle: '📜 | ZASADY OGÓLNE (15)',
    generalDesc: `**1.** Traktujcie się nawzajem z szacunkiem i godnością.\n**2.** Zakaz jakiejkolwiek formy dyskryminacji, rasizmu czy wyzwisk.\n**3.** Szanuj prywatność innych użytkowników.\n**4.** Zakaz rozpowszechniania cudzych danych osobowych (doxxing).\n**5.** Nie prowokuj kłótni ani toksycznych dyskusji.\n**6.** Nie wykorzystuj błędów ani luk w regulaminie serwera.\n**7.** Przestrzegaj obowiązującego prawa i regulacji UE.\n**8.** Udostępnianie nieodpowiednich lub nielegalnych treści (NSFW/NSFL itp.) jest surowo zabronione.\n**9.** Moderatorzy i Administratorzy mają zawsze ostatnie słowo; ich decyzje muszą być szanowane.\n**10.** Rozwiązujcie skargi i nieporozumienia z administracją za pomocą ticketów, a nie publicznie na czacie.\n**11.** Zakaz dyskusji politycznych, ekstremistycznych i religijnych.\n**12.** Zakaz podszywania się pod innych użytkowników, gwiazdy lub członków administracji.\n**13.** Zakaz jakichkolwiek form reklamy poza wyznaczonymi kanałami lub bez pozwolenia.\n**14.** Nie trolluj i nie niszcz celowo wrażeń z gry innym.\n**15.** Używaj zdrowego rozsądku – jeśli jakaś sytuacja nie jest opisana w regulaminie, obowiązuje zasada zdrowego rozsądku i etyki.`,
    
    discordTitle: '💬 | ZASADY DISCORD (18)',
    discordDesc: `**1.** Zakaz nieuzasadnionego pingowania (oznaczania) członków, a zwłaszcza administracji.\n**2.** Zakaz pingowania dużych ról, takich jak @everyone lub @here.\n**3.** Zdjęcie profilowe i baner nie mogą zawierać treści nieodpowiednich, wulgarnych ani rasistowskich.\n**4.** Pseudonim musi być czytelny (łatwy do oznaczenia) i nie może zawierać wulgarnych znaków ani słów.\n**5.** Nie spamuj czatu (powtarzające się bezsensowne wiadomości).\n**6.** Nie flooduj czatu (rozbijanie jednej wiadomości na dziesiątki krótkich).\n**7.** Zakaz nadmiernego używania wielkich liter (CAPS LOCK).\n**8.** Utrzymuj kanały zgodnie z ich przeznaczeniem (off-topic, komendy botów, memy...).\n**9.** Nie wysyłaj linków do podejrzanych, phishingowych lub niebezpiecznych stron.\n**10.** Zakaz "Ghost Pingu" (oznaczenie i szybkie usunięcie wiadomości).\n**11.** Nie wydawaj irytujących dźwięków na kanałach głosowych (dmuchanie w mikrofon, krzyk, spam soundboardem).\n**12.** Nie używaj modulatorów głosu bez zgody innych.\n**13.** Jeśli odtwarzasz muzykę, miej na uwadze innych słuchaczy.\n**14.** Zakaz streamowania nieodpowiednich filmów na kanałach głosowych.\n**15.** Zakaz żebrania o rangi, specjalne prawa lub przywileje.\n**16.** Zachowuj się kulturalnie; ogranicz wulgaryzmy do minimum.\n**17.** Nie przeszkadzaj w toczących się rozmowach na kanałach głosowych.\n**18.** Przestrzegaj oficjalnych zasad (TOS) oraz wytycznych społeczności platformy Discord.`,

    serverTitle: '🛡️ | ZASADY SERWERA (10)',
    serverDesc: `**1.** Zakaz używania nieoficjalnych lub nieautoryzowanych klientów, cheatów lub hacków.\n**2.** Wykorzystywanie błędów i luk jest zakazane. Zgłaszaj je administracji.\n**3.** Szanuj wszystkich innych graczy i nie niszcz celowo ich rozgrywki.\n**4.** Zakaz Griefingu: Niszczenie i uszkadzanie własności oraz pracy innych bez powodu jest zabronione.\n**5.** Tworzenie maszyn lagujących serwer jest surowo karane.\n**6.** Wszelkie formy oszustw pomiędzy graczami (Scamming) są surowo zabronione.\n**7.** Twoje maszyny i automatyzacje nie mogą nieproporcjonalnie obciążać wydajności serwera.\n**8.** Graj fair-play w każdej sytuacji; staramy się budować fajną społeczność.\n**9.** Dozwolone jest tylko jedno konto na użytkownika (zakaz używania multikont be zezwolenia).\n**10.** Zakaz handlu na czarnym rynku wirtualnymi przedmiotami za prawdziwe pieniądze.`,

    mcTitle: '⛏️ | ZASADY MINECRAFT (14)',
    mcDesc: `**1.** X-Ray oraz wszelkie modyfikacje ułatwiające nielegalne znajdowanie rud są surowo zabronione.\n**2.** Baritone (automatyczne kopanie) i inne boty są karane banem.\n**3.** AFK i farmienie: Dozwolone, ale przy ogromnych i obciążających farmach możesz zostać poproszony o ich ograniczenie.\n**4.** Zakaz kopiowania (dupe) przedmiotów, bloków ani XP.\n**5.** Kradzież przedmiotów i pieniędzy z prywatnych skrzynek graczy jest surowo zabroniona.\n**6.** Pozostaw obszar spawnu nietknięty; budowanie lub niszczenie natury blisko spawnu jest zabronione.\n**7.** Zakaz budowania nieodpowiednich i obraźliwych konstrukcji.\n**8.** Zabijanie innych graczy (PVP) bez ich zgody jest zabronione (zakaz RDM).\n**9.** Zakaz trollingu (np. zwabianie graczy w pułapki TP).\n**10.** Ścinanie drzew musi być całkowite - od dołu do góry (nie zostawiaj lewitujących liści ani drewna).\n**11.** Zniszcz brzydkie kolumny (słupy używane do rozglądania się) od razu po ich użyciu.\n**12.** Administracja ma prawo zmodyfikować Twoją budowlę/zwierzęta w przypadku spadku TPS (lagów).\n**13.** Zakaz spamowania na czacie gry oraz w MSG (wiadomości prywatne).\n**14.** Ponosisz wyłączną odpowiedzialność za swoje konto (włamanie lub gra młodszego brata = Twój problem).`
  }
};
